variable "project" {
  type = string
}

variable "environment" {
  type = string
}

variable "site_host" {
  description = "Fully-qualified host this distribution serves, e.g. stephen.naijora.com."
  type        = string
}

variable "hosted_zone_id" {
  description = "Existing zone. Read by the caller, never created here: the zone also carries MX and TXT records for the apex, and a destroy that removed it would take the domain's email with it."
  type        = string
}

variable "certificate_arn" {
  description = "Existing ISSUED certificate in us-east-1 covering site_host. Passed in rather than requested, because the account already holds a wildcard covering this name and a duplicate would add validation records to a shared zone for no benefit."
  type        = string
}

variable "price_class" {
  description = "PriceClass_100 is North America and Europe. The cheapest tier, and adequate unless traffic is genuinely global."
  type        = string
  default     = "PriceClass_100"
}

variable "csp_script_hashes" {
  description = "SHA-256 of every inline script, theme-init included. Empty means script-src is omitted rather than shipping a policy that blocks the theme script. Generated by scripts/csp-hashes.mjs."
  type        = list(string)
  default     = []
}

variable "alarm_sns_topic_arn" {
  description = "Where the 5xx alarm publishes. Empty disables the alarm action but still creates the alarm, so the metric is visible in the console."
  type        = string
  default     = ""
}
